# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hackarc

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      working-directory: apps/hackARC2020
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hackarc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77b8fdae8e114dd8bc63f385f4d09164 }}
        package: .
